// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webshop.Infrastructure.EF;

#nullable disable

namespace Webshop.Infrastructure.Migrations
{
    [DbContext(typeof(WebshopDbContext))]
    [Migration("20260414100042_MobilnummerSomSträng")]
    partial class MobilnummerSomSträng
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Webshop.Domain.Entitites.FraktOmbud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FraktOmbud");
                });

            modelBuilder.Entity("Webshop.Domain.Entitites.Kategori", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Kategorier");
                });

            modelBuilder.Entity("Webshop.Domain.Entitites.Kund", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Epost")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("MobilNummer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Postnummer")
                        .HasColumnType("int");

                    b.Property<string>("Stad")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Kunder");
                });

            modelBuilder.Entity("Webshop.Domain.Entitites.Leverantör", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Leverantörer");
                });

            modelBuilder.Entity("Webshop.Domain.Entitites.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Betalsätt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FraktOmbudId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDatum")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ÄrBetald")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FraktOmbudId");

                    b.HasIndex("KundId");

                    b.ToTable("Ordrar");
                });

            modelBuilder.Entity("Webshop.Domain.Entitites.Produkt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Beskrivning")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Färg")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("KategoriId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LagerAntal")
                        .HasColumnType("int");

                    b.Property<Guid>("LeverantörId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Storlek")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ÄrUtvald")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("LeverantörId");

                    b.ToTable("Produkter");
                });

            modelBuilder.Entity("Webshop.Domain.Entitites.ProduktOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrisvidKöp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProduktId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProduktId");

                    b.ToTable("ProduktOrdrar");
                });

            modelBuilder.Entity("Webshop.Domain.Entitites.Order", b =>
                {
                    b.HasOne("Webshop.Domain.Entitites.FraktOmbud", "FraktOmbud")
                        .WithMany("Ordrar")
                        .HasForeignKey("FraktOmbudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Webshop.Domain.Entitites.Kund", "Kund")
                        .WithMany("Ordrar")
                        .HasForeignKey("KundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FraktOmbud");

                    b.Navigation("Kund");
                });

            modelBuilder.Entity("Webshop.Domain.Entitites.Produkt", b =>
                {
                    b.HasOne("Webshop.Domain.Entitites.Kategori", "Kategori")
                        .WithMany("Produkter")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Webshop.Domain.Entitites.Leverantör", "Leverantör")
                        .WithMany("Produkter")
                        .HasForeignKey("LeverantörId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Leverantör");
                });

            modelBuilder.Entity("Webshop.Domain.Entitites.ProduktOrder", b =>
                {
                    b.HasOne("Webshop.Domain.Entitites.Order", "Order")
                        .WithMany("ProduktOrdrar")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webshop.Domain.Entitites.Produkt", "Produkt")
                        .WithMany("ProduktOrdrar")
                        .HasForeignKey("ProduktId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Produkt");
                });

            modelBuilder.Entity("Webshop.Domain.Entitites.FraktOmbud", b =>
                {
                    b.Navigation("Ordrar");
                });

            modelBuilder.Entity("Webshop.Domain.Entitites.Kategori", b =>
                {
                    b.Navigation("Produkter");
                });

            modelBuilder.Entity("Webshop.Domain.Entitites.Kund", b =>
                {
                    b.Navigation("Ordrar");
                });

            modelBuilder.Entity("Webshop.Domain.Entitites.Leverantör", b =>
                {
                    b.Navigation("Produkter");
                });

            modelBuilder.Entity("Webshop.Domain.Entitites.Order", b =>
                {
                    b.Navigation("ProduktOrdrar");
                });

            modelBuilder.Entity("Webshop.Domain.Entitites.Produkt", b =>
                {
                    b.Navigation("ProduktOrdrar");
                });
#pragma warning restore 612, 618
        }
    }
}
