<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>00c534ec-185f-471e-b564-0d04b18b7f9d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DisplayService\" />
    <Folder Include="UI\NewFolder\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Webshop.Application\Webshop.Application.csproj" />
    <ProjectReference Include="..\Webshop.Domain\Webshop.Domain.csproj" />
    <ProjectReference Include="..\Webshop.Infrastructure\Webshop.Infrastructure.csproj" />
  </ItemGroup>

</Project>
